#!/command/with-contenv bash
# shellcheck shell=bash
# Start the comms-dispatcher Rust daemon

set -o errexit -o nounset -o pipefail

exec 2>&1
echo "[INFO] Starting comms-dispatcher..."
exec /usr/local/bin/comms-dispatcher
