#!/command/with-contenv bash
# shellcheck shell=bash
set -o errexit -o nounset -o pipefail
readonly exit_code_service="${1}"
readonly exit_code_signal="${2}"
echo "[INFO] The storage-daemon service exited with code ${exit_code_service} (by signal ${exit_code_signal})"
